---
#-------------------------------
# General Site Settings

title: Portfolio
logo:
author: themefisher
description: this is meta description
email: vedant.singhania@gmail.com
phone: +1 202 644 2636
address: 125/A, CA Commercial Area, California, USA
copyright: Copyright 2024 Vedant Singhania

menu:
  - { name: About, link: "/about" }
  - { name: Blog, link: "/blog" }
  - { name: Projects, link: "/projects" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Vedant Singhania <br>

#-------------------------------
# About (Section and Page)

# About Section
blurb: Welcome! My name is Vedant Singhania and I am from Palo Alto, California. I have been coding since I was 12 and since then, I have become highly proficient in HTML, Python, Java, and JavaScript, and various frameworks and libraries, I have taken college-level computer science courses in high school, and I am now in the midst of my first year as a computer science major at San José State University. While I enjoy working on my own projects to help people in their everyday lives, I also have a passion for contributing to open source code in the community.


blurb-btn-link: "/about"
blurb-btn-name: learn more

# Skills Section

skills-title: Skills
skills:
  - { name: Application Architecture, color: "#fdb157", value: "75%" }
  - { name: UI/UX Design, color: "#9473e6", value: "75%" }
  - { name: Backend Engineering, color: "#bdecf6", value: "75%" }
  - { name: API Integration, color: "#a3d9a5", value: "75%" }
#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
      name:  Backend Integration Engineering Intern,
      icon: "icon-2.png",
      date: "May 2024 - Present",
      organization: "Y STEM AND CHESS",
    }
  - {
      name: Web Team Lead,
      icon: "icon-3.png",
      date: "June 2021 - May 2023",
      organization: "BIG BRAINERS",
    }

#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: High School Diploma,
      date: "May 2023",
      organization: "Palo Alto High School",
    }
  - {
      name: Bachelor's of Science in Computer Science,
      date: "Expected Graduation: May 2027",
      organization: "San José State University",
    }
#-------------------------------

# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "projects#taskorial"
    name: "Taskorial"
    id: "taskorial"

  - image: "assets/images/portfolio/item-2.png"
    name: "Tunestats"
    id: "tunestats"

  - image: "assets/images/portfolio/item-3.png"
    url: "projects#accessguide"
    name: "AccessGuide"
    id: "accessguide"

  - image: "assets/images/portfolio/item-4.png"
    url: "projects#chairsense"
    name: "ChairSense"
    id: "chairsense"

  - image: "assets/images/portfolio/item-5.png"
    url: "projects#cli"
    name: "CLI"
    id: "cli"

# Portfolio Page
portfolio-label:
  - { title: "Web/App Development", type: "web" }
  - { title: "Hardware Programming", type: "branding" }
  - { title: "Command Line Applications", type: "illustration" }

portfolio-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#taskorial"
    portfolio-type:
      - type: "design"
      - type: "web"
    name: "Taskorial"
    id: "taskorial"
    date: "spring 2024"
    description: "A full-stack web application to keep track of your tasks, with Google Gemini-powered AI integration in active development. I built this using React for the frontend, Express for the backend, and MongoDB for the database. This project also integrates Google's Gemini AI via a server-side API.

"

  - image: "assets/images/portfolio/item-2.png"
    url: "#tunestats"
    portfolio-type:
      - type: "web"
    name: "Tunestats"
    id: "tunestats"
    date: ""
    description: "A full-stack web application for Spotify users to see listening stats such as top songs and artists, and to view recently played songs. This was built with React, Express, and the Spotify API. This was my first major full stack web development project."

  - image: "assets/images/portfolio/item-3.png"
    url: "#accessguide"
    portfolio-type:
      - type: "web"
    name: "AccessGuide"
    id: "access-guide"
    date: ""
    description: ""

  - image: "assets/images/portfolio/item-4.png"
    url: "#chairsense"
    portfolio-type:
      - type: "branding"
    name: "ChairSense"
    id: "chairsense"
    date: ""
    description: "For wheelchair users, it can be hard to see what's behind the chair, especially when backing up or turning, which can be dangerous because there is a high potential to hit an object or person. The aim of this project is to solve that problem by creating a low-cost device that can detect obstacles and warn the wheelchair user so they don't hit objects or people."
    whitepaper: "assets/documents/chairSense_Research_Paper.pdf"
    demo: "https://www.youtube.com/watch?v=z72_hVvBnQc"

  - image: "assets/images/portfolio/item-5.png"
    url: "#cli"
    portfolio-type:
      - type: "illustration"
    name: "CLI"
    id: "cli"
    date: ""
    description: ""
